#
# huawei battery drivers
#

obj-$(CONFIG_HUAWEI_BATTERY_MODEL) += battery_model/
obj-$(CONFIG_HUAWEI_BATTERY_UI_CAPACTIY) += battery_ui_capacity/
obj-$(CONFIG_HUAWEI_BATTERY_FAULT) += battery_fault/
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_soh/

obj-$(CONFIG_HUAWEI_BATTERY_CORE) += battery_core.o
