#
# huawei hardware monitor drivers
#

obj-$(CONFIG_HUAWEI_WATER_DETECT) += water_detect/
obj-$(CONFIG_HUAWEI_SOC_CONTROL) += soc_control/
obj-$(CONFIG_HUAWEI_BAT_HEATING) += bat_heating/
obj-$(CONFIG_HUAWEI_TEMP_CONTROL) += temp_control/
obj-$(CONFIG_HUAWEI_BTB_CHECK) += btb_check/
obj-$(CONFIG_HUAWEI_FFC_CONTROL) += ffc_control/
